In [29]:
import pandas as pd
import numpy as np

In [36]:
fortune = pd.read_csv('dane/course-files/Fortune_500_2017.csv')
fortune.head()

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
0,1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
1,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
2,3,Apple,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
3,4,Exxon Mobil,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
4,5,McKesson,http://www.mckesson.com,68000,Wholesalers,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0

In [37]:
fortune.set_index('Rank', inplace = True)
fortune.head()

,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,Hqzip,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Rank,,,,,,,,,,,,,,,,,,,,,
1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,72716,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,68131,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
3,Apple,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,95014,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
4,Exxon Mobil,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,75039,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
5,McKesson,http://www.mckesson.com,68000,Wholesalers,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,94104,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0

In [39]:
fortune.loc[100:105]

,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,Hqzip,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Rank,,,,,,,,,,,,,,,,,,,,,
100,Capital One Financial,http://www.capitalone.com,47300,Financials,Commercial Banks,"McLean, VA",1680 Capital One Dr.,McLean,VA,22102,...,"Chairman, President & Chief Executive Officer","1680 Capital One Dr., McLean, VA 22102",COF,Capital One Financial Corporation,27519,9.6,3751.0,-7.4,357033,47514.0
101,Twenty-First Century Fox,http://www.21cf.com,21500,Media,Entertainment,"New York, NY",1211 Ave. of the Americas,New York,NY,10036,...,Chief Executive Officer & Director,"1211 Ave. of the Americas, New York, NY 10036",FOXA,"Twenty-First Century Fox, Inc.",27326,-5.7,2755.0,-66.8,48365,13661.0
102,USAA,http://www.usaa.com,29943,Financials,Insurance: Property and Casualty (Stock),"San Antonio, TX",9800 Fredericksburg Rd.,San Antonio,TX,78288,...,"President, Chief Executive Officer & Director","9800 Fredericksburg Rd., San Antonio, TX 78288",FOXA,United Services Automobile Association,27131,11.4,1779.1,-21.7,147290,28840.0
103,World Fuel Services,http://www.wfscorp.com,5000,Energy,Energy,"Miami, FL",9800 N.W. 41st St.,Miami,FL,33178,...,"Chairman, President & Chief Executive Officer","9800 N.W. 41st St., Miami, FL 33178",INT,World Fuel Services Corporation,27016,-11.1,126.5,-27.5,5413,1925.0
104,Philip Morris International,http://www.pmi.com,79500,"Food, Beverages & Tobacco",Tobacco,"New York, NY",120 Park Ave.,New York,NY,10017,...,Chief Executive Officer & Director,"120 Park Ave., New York, NY 10017",PM,Philip Morris International Inc.,26685,-0.4,6967.0,1.4,36851,-12688.0
105,Deere,http://www.johndeere.com,56767,Industrials,Construction and Farm Machinery,"Moline, IL",1 John Deere Place,Moline,IL,61265,...,Chairman & Chief Executive Officer,"1 John Deere Place, Moline, IL 61265",DE,Deere & Company,26644,-7.7,1523.9,-21.4,57981,6520.0

In [43]:
fortune.loc[100:105][['Title', 'Employees']]

                            Title  Employees
Rank
100         Capital One Financial      47300
101      Twenty-First Century Fox      21500
102                          USAA      29943
103           World Fuel Services       5000
104   Philip Morris International      79500
105                         Deere      56767

In [46]:
fortune.reset_index(inplace=True)

In [47]:
fortune.set_index('Title', inplace=True)
fortune.head()

,Rank,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,Hqzip,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Title,,,,,,,,,,,,,,,,,,,,,
Walmart,1,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,72716,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
Berkshire Hathaway,2,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,68131,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
Apple,3,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,95014,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
Exxon Mobil,4,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,75039,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
McKesson,5,http://www.mckesson.com,68000,Wholesalers,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,94104,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0

In [49]:
fortune.sort_index(inplace=True)
fortune.head()

,Rank,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,Hqzip,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Title,,,,,,,,,,,,,,,,,,,,,
3M,94,http://www.3m.com,91584,Industrials,Miscellaneous,"St. Paul, MN",3M Center,St. Paul,MN,55144,...,"Chairman, President & Chief Executive Officer","3M Center, St. Paul, MN 55144",MMM,3M Company,30109,-0.5,5050.0,4.5,32906,10298.0
A-Mark Precious Metals,395,http://www.amark.com,83,Materials,Miscellaneous,"Santa Monica, CA",429 Santa Monica Blvd.,Santa Monica,CA,90401,...,Chief Executive Officer & Director,"429 Santa Monica Blvd., Santa Monica, CA 90401",AMRK,"A-Mark Precious Metals, Inc.",6784,11.8,9.3,31.5,437,63.0
ABM Industries,500,http://www.abm.com,110000,Business Services,Diversified Outsourcing Services,"New York, NY",1 Liberty Plaza,New York,NY,10006,...,"President, Chief Executive Officer & Director","1 Liberty Plaza, New York, NY 10006",ABM,ABM Industries Incorporated,5145,-2.8,57.2,-25,2281,974.0
ADP,240,http://www.adp.com,57000,Business Services,Diversified Outsourcing Services,"Roseland, NJ",1 ADP Blvd.,Roseland,NJ,7068,...,"President, Chief Executive Officer & Director","1 ADP Blvd., Roseland, NJ 07068",ADP,"Automatic Data Processing, Inc.",11668,1.7,1492.5,2.8,43670,4482.0
AECOM,161,http://www.aecom.com,87000,Engineering & Construction,"Engineering, Construction","Los Angeles, CA",1999 Ave. of the Stars,Los Angeles,CA,90067,...,Chairman & Chief Executive Officer,"1999 Ave. of the Stars, Los Angeles, CA 90067",ACM,AECOM,17411,-3.2,96.1,-28.7,13727,3367.0

In [50]:
fortune.loc['X':'Y']

,Rank,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,Hqzip,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Title,,,,,,,,,,,,,,,,,,,,,
XPO Logistics,191,http://www.xpo.com,87000,Transportation,Transportation and Logistics,"Greenwich, CT",5 American Lane,Greenwich,CT,6831,...,Chairman & Chief Executive Officer,"5 American Lane, Greenwich, CT 06831",XPO,"XPO Logistics, Inc.",14619,91.8,69.0,-178.2,11698,2700.0
Xcel Energy,256,http://www.xcelenergy.com,11476,Energy,Utilities: Gas and Electric,"Minneapolis, MN",414 Nicollet Mall,Minneapolis,MN,55401,...,"Chairman, President & Chief Executive Officer","414 Nicollet Mall, Minneapolis, MN 55401",XEL,Xcel Energy Inc.,11107,0.7,1123.4,14.1,41155,11021.0
Xerox,162,http://www.xerox.com,133600,Technology,Computer Peripherals,"Norwalk, CT",45 Glover Ave.,Norwalk,CT,6850,...,Chief Executive Officer & Director,"45 Glover Ave., Norwalk, CT 06850",XRX,Xerox Corporation,17126,-8.2,-477.0,-200.6,18145,4803.0