In [1]:
import pandas as pd
import numpy as np

In [2]:
air = pd.read_csv("dane/course-files/Air_Traffic_Passenger_Statistics.csv")
air.head()

,Activity Period,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Activity Type Code,Price Category Code,Terminal,Boarding Area,Passenger Count
0,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Deplaned,Low Fare,Terminal 1,B,27271
1,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Enplaned,Low Fare,Terminal 1,B,29131
2,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Thru / Transit,Low Fare,Terminal 1,B,5415
3,200507,Air Canada,AC,Air Canada,AC,International,Canada,Deplaned,Other,Terminal 1,B,35156
4,200507,Air Canada,AC,Air Canada,AC,International,Canada,Enplaned,Other,Terminal 1,B,34090

In [3]:
air.set_index(["Operating Airline", "Activity Period"], inplace = True)
air.head(10)

                                  Operating Airline IATA Code  \
Operating Airline Activity Period
ATA Airlines      200507                                   TZ
                  200507                                   TZ
                  200507                                   TZ
Air Canada        200507                                   AC
                  200507                                   AC
Air China         200507                                   CA
                  200507                                   CA
Air France        200507                                   AF
                  200507                                   AF
Air New Zealand   200507                                   NZ

                                  Published Airline  \
Operating Airline Activity Period
ATA Airlines      200507               ATA Airlines
                  200507               ATA Airlines
                  200507               ATA Airlines
Air Canada        200507                 Air Canada
                  200507                 Air Canada
Air China         200507                  Air China
                  200507                  Air China
Air France        200507                 Air France
                  200507                 Air France
Air New Zealand   200507            Air New Zealand

                                  Published Airline IATA Code    GEO Summary  \
Operating Airline Activity Period
ATA Airlines      200507                                   TZ       Domestic
                  200507                                   TZ       Domestic
                  200507                                   TZ       Domestic
Air Canada        200507                                   AC  International
                  200507                                   AC  International
Air China         200507                                   CA  International
                  200507                                   CA  International
Air France        200507                                   AF  International
                  200507                                   AF  International
Air New Zealand   200507                                   NZ  International

                                            GEO Region Activity Type Code  \
Operating Airline Activity Period
ATA Airlines      200507                            US           Deplaned
                  200507                            US           Enplaned
                  200507                            US     Thru / Transit
Air Canada        200507                        Canada           Deplaned
                  200507                        Canada           Enplaned
Air China         200507                          Asia           Deplaned
                  200507                          Asia           Enplaned
Air France        200507                        Europe           Deplaned
                  200507                        Europe           Enplaned
Air New Zealand   200507           Australia / Oceania           Deplaned

                                  Price Category Code       Terminal  \
Operating Airline Activity Period
ATA Airlines      200507                     Low Fare     Terminal 1
                  200507                     Low Fare     Terminal 1
                  200507                     Low Fare     Terminal 1
Air Canada        200507                        Other     Terminal 1
                  200507                        Other     Terminal 1
Air China         200507                        Other  International
                  200507                        Other  International
Air France        200507                        Other  International
                  200507                        Other  International
Air New Zealand   200507                        Other  International

                                  Boarding Area  Passenger Count
Operating Airline Activity Period
ATA Airlines      200507                      B            27271
                  200507                      B            29131
                  200507                      B             5415
Air Canada        200507                      B            35156
                  200507                      B            34090
Air China         200507                      G             6263
                  200507                      G             5500
Air France        200507                      A            12050
                  200507                      A            11638
Air New Zealand   200507                      G             4998

In [4]:
air.reset_index(inplace=True)
air.head()

,Operating Airline,Activity Period,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Activity Type Code,Price Category Code,Terminal,Boarding Area,Passenger Count
0,ATA Airlines,200507,TZ,ATA Airlines,TZ,Domestic,US,Deplaned,Low Fare,Terminal 1,B,27271
1,ATA Airlines,200507,TZ,ATA Airlines,TZ,Domestic,US,Enplaned,Low Fare,Terminal 1,B,29131
2,ATA Airlines,200507,TZ,ATA Airlines,TZ,Domestic,US,Thru / Transit,Low Fare,Terminal 1,B,5415
3,Air Canada,200507,AC,Air Canada,AC,International,Canada,Deplaned,Other,Terminal 1,B,35156
4,Air Canada,200507,AC,Air Canada,AC,International,Canada,Enplaned,Other,Terminal 1,B,34090

In [5]:
air.set_index(["Activity Period", "Operating Airline"],inplace= True)
air.head(10)

                                  Operating Airline IATA Code  \
Activity Period Operating Airline
200507          ATA Airlines                               TZ
                ATA Airlines                               TZ
                ATA Airlines                               TZ
                Air Canada                                 AC
                Air Canada                                 AC
                Air China                                  CA
                Air China                                  CA
                Air France                                 AF
                Air France                                 AF
                Air New Zealand                            NZ

                                  Published Airline  \
Activity Period Operating Airline
200507          ATA Airlines           ATA Airlines
                ATA Airlines           ATA Airlines
                ATA Airlines           ATA Airlines
                Air Canada               Air Canada
                Air Canada               Air Canada
                Air China                 Air China
                Air China                 Air China
                Air France               Air France
                Air France               Air France
                Air New Zealand     Air New Zealand

                                  Published Airline IATA Code    GEO Summary  \
Activity Period Operating Airline
200507          ATA Airlines                               TZ       Domestic
                ATA Airlines                               TZ       Domestic
                ATA Airlines                               TZ       Domestic
                Air Canada                                 AC  International
                Air Canada                                 AC  International
                Air China                                  CA  International
                Air China                                  CA  International
                Air France                                 AF  International
                Air France                                 AF  International
                Air New Zealand                            NZ  International

                                            GEO Region Activity Type Code  \
Activity Period Operating Airline
200507          ATA Airlines                        US           Deplaned
                ATA Airlines                        US           Enplaned
                ATA Airlines                        US     Thru / Transit
                Air Canada                      Canada           Deplaned
                Air Canada                      Canada           Enplaned
                Air China                         Asia           Deplaned
                Air China                         Asia           Enplaned
                Air France                      Europe           Deplaned
                Air France                      Europe           Enplaned
                Air New Zealand    Australia / Oceania           Deplaned

                                  Price Category Code       Terminal  \
Activity Period Operating Airline
200507          ATA Airlines                 Low Fare     Terminal 1
                ATA Airlines                 Low Fare     Terminal 1
                ATA Airlines                 Low Fare     Terminal 1
                Air Canada                      Other     Terminal 1
                Air Canada                      Other     Terminal 1
                Air China                       Other  International
                Air China                       Other  International
                Air France                      Other  International
                Air France                      Other  International
                Air New Zealand                 Other  International

                                  Boarding Area  Passenger Count
Activity Period Operating Airline
200507          ATA Airlines                  B            27271
                ATA Airlines                  B            29131
                ATA Airlines                  B             5415
                Air Canada                    B            35156
                Air Canada                    B            34090
                Air China                     G             6263
                Air China                     G             5500
                Air France                    A            12050
                Air France                    A            11638
                Air New Zealand               G             4998

In [6]:
air.sort_index(ascending = [False, True], inplace=True)
air.head(10)

                                                         Operating Airline IATA Code  \
Activity Period Operating Airline
201803          ABC Aerolineas S.A. de C.V. dba Interjet                          4O
                ABC Aerolineas S.A. de C.V. dba Interjet                          4O
                Aer Lingus                                                        EI
                Aer Lingus                                                        EI
                Aeromexico                                                        AM
                Aeromexico                                                        AM
                Air Canada                                                        AC
                Air Canada                                                        AC
                Air China                                                         CA
                Air China                                                         CA

                                                                                 Published Airline  \
Activity Period Operating Airline
201803          ABC Aerolineas S.A. de C.V. dba Interjet  ABC Aerolineas S.A. de C.V. dba Interjet
                ABC Aerolineas S.A. de C.V. dba Interjet  ABC Aerolineas S.A. de C.V. dba Interjet
                Aer Lingus                                                              Aer Lingus
                Aer Lingus                                                              Aer Lingus
                Aeromexico                                                              Aeromexico
                Aeromexico                                                              Aeromexico
                Air Canada                                                              Air Canada
                Air Canada                                                              Air Canada
                Air China                                                                Air China
                Air China                                                                Air China

                                                         Published Airline IATA Code  \
Activity Period Operating Airline
201803          ABC Aerolineas S.A. de C.V. dba Interjet                          4O
                ABC Aerolineas S.A. de C.V. dba Interjet                          4O
                Aer Lingus                                                        EI
                Aer Lingus                                                        EI
                Aeromexico                                                        AM
                Aeromexico                                                        AM
                Air Canada                                                        AC
                Air Canada                                                        AC
                Air China                                                         CA
                Air China                                                         CA

                                                            GEO Summary  \
Activity Period Operating Airline
201803          ABC Aerolineas S.A. de C.V. dba Interjet  International
                ABC Aerolineas S.A. de C.V. dba Interjet  International
                Aer Lingus                                International
                Aer Lingus                                International
                Aeromexico                                International
                Aeromexico                                International
                Air Canada                                International
                Air Canada                                International
                Air China                                 International
                Air China                                 International

                                                         GEO Region  \
Activity Period Operating Airline
201803          ABC Aerolineas S.A. de C.V. dba Interjet     Mexico
                ABC Aerolineas S.A. de C.V. dba Interjet     Mexico
                Aer Lingus                                   Europe
                Aer Lingus                                   Europe
                Aeromexico                                   Mexico
                Aeromexico                                   Mexico
                Air Canada                                   Canada
                Air Canada                                   Canada
                Air China                                      Asia
                Air China                                      Asia

                                                         Activity Type Code  \
Activity Period Operating Airline
201803          ABC Aerolineas S.A. de C.V. dba Interjet           Deplaned
                ABC Aerolineas S.A. de C.V. dba Interjet           Enplaned
                Aer Lingus                                         Deplaned
                Aer Lingus                                         Enplaned
                Aeromexico                                         Deplaned
                Aeromexico                                         Enplaned
                Air Canada                                         Deplaned
                Air Canada                                         Enplaned
                Air China                                          Deplaned
                Air China                                          Enplaned

                                                         Price Category Code  \
Activity Period Operating Airline
201803          ABC Aerolineas S.A. de C.V. dba Interjet               Other
                ABC Aerolineas S.A. de C.V. dba Interjet               Other
                Aer Lingus                                             Other
                Aer Lingus                                             Other
                Aeromexico                                             Other
                Aeromexico                                             Other
                Air Canada                                             Other
                Air Canada                                             Other
                Air China                                              Other
                Air China                                              Other

                                                               Terminal  \
Activity Period Operating Airline
201803          ABC Aerolineas S.A. de C.V. dba Interjet  International
                ABC Aerolineas S.A. de C.V. dba Interjet  International
                Aer Lingus                                International
                Aer Lingus                                International
                Aeromexico                                International
                Aeromexico                                International
                Air Canada                                International
                Air Canada                                International
                Air China                                 International
                Air China                                 International

                                                         Boarding Area  \
Activity Period Operating Airline
201803          ABC Aerolineas S.A. de C.V. dba Interjet             A
                ABC Aerolineas S.A. de C.V. dba Interjet             A
                Aer Lingus                                           G
                Aer Lingus                                           G
                Aeromexico                                           A
                Aeromexico                                           A
                Air Canada                                           G
                Air Canada                                           G
                Air China                                            G
                Air China                                            G

                                                          Passenger Count
Activity Period Operating Airline
201803          ABC Aerolineas S.A. de C.V. dba Interjet             1090
                ABC Aerolineas S.A. de C.V. dba Interjet             1212
                Aer Lingus                                           7165
                Aer Lingus                                           6992
                Aeromexico                                          12334
                Aeromexico                                          12125
                Air Canada                                          36266
                Air Canada                                          38934
                Air China                                            9154
                Air China                                            9577

In [11]:
air.reset_index(inplace=True)
air.head()

,Activity Period,Operating Airline,Activity Type Code,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Price Category Code,Terminal,Boarding Area,Passenger Count
0,201803,ABC Aerolineas S.A. de C.V. dba Interjet,Deplaned,4O,ABC Aerolineas S.A. de C.V. dba Interjet,4O,International,Mexico,Other,International,A,1090
1,201803,ABC Aerolineas S.A. de C.V. dba Interjet,Enplaned,4O,ABC Aerolineas S.A. de C.V. dba Interjet,4O,International,Mexico,Other,International,A,1212
2,201803,Aer Lingus,Deplaned,EI,Aer Lingus,EI,International,Europe,Other,International,G,7165
3,201803,Aer Lingus,Enplaned,EI,Aer Lingus,EI,International,Europe,Other,International,G,6992
4,201803,Aeromexico,Deplaned,AM,Aeromexico,AM,International,Mexico,Other,International,A,12334

In [12]:
air.set_index(["Activity Period","Operating Airline","Activity Type Code"],inplace=True)
air.head(10)

                                                                            Operating Airline IATA Code  \
Activity Period Operating Airline                        Activity Type Code
201803          ABC Aerolineas S.A. de C.V. dba Interjet Deplaned                                    4O
                                                         Enplaned                                    4O
                Aer Lingus                               Deplaned                                    EI
                                                         Enplaned                                    EI
                Aeromexico                               Deplaned                                    AM
                                                         Enplaned                                    AM
                Air Canada                               Deplaned                                    AC
                                                         Enplaned                                    AC
                Air China                                Deplaned                                    CA
                                                         Enplaned                                    CA

                                                                                                    Published Airline  \
Activity Period Operating Airline                        Activity Type Code
201803          ABC Aerolineas S.A. de C.V. dba Interjet Deplaned            ABC Aerolineas S.A. de C.V. dba Interjet
                                                         Enplaned            ABC Aerolineas S.A. de C.V. dba Interjet
                Aer Lingus                               Deplaned                                          Aer Lingus
                                                         Enplaned                                          Aer Lingus
                Aeromexico                               Deplaned                                          Aeromexico
                                                         Enplaned                                          Aeromexico
                Air Canada                               Deplaned                                          Air Canada
                                                         Enplaned                                          Air Canada
                Air China                                Deplaned                                           Air China
                                                         Enplaned                                           Air China

                                                                            Published Airline IATA Code  \
Activity Period Operating Airline                        Activity Type Code
201803          ABC Aerolineas S.A. de C.V. dba Interjet Deplaned                                    4O
                                                         Enplaned                                    4O
                Aer Lingus                               Deplaned                                    EI
                                                         Enplaned                                    EI
                Aeromexico                               Deplaned                                    AM
                                                         Enplaned                                    AM
                Air Canada                               Deplaned                                    AC
                                                         Enplaned                                    AC
                Air China                                Deplaned                                    CA
                                                         Enplaned                                    CA

                                                                               GEO Summary  \
Activity Period Operating Airline                        Activity Type Code
201803          ABC Aerolineas S.A. de C.V. dba Interjet Deplaned            International
                                                         Enplaned            International
                Aer Lingus                               Deplaned            International
                                                         Enplaned            International
                Aeromexico                               Deplaned            International
                                                         Enplaned            International
                Air Canada                               Deplaned            International
                                                         Enplaned            International
                Air China                                Deplaned            International
                                                         Enplaned            International

                                                                            GEO Region  \
Activity Period Operating Airline                        Activity Type Code
201803          ABC Aerolineas S.A. de C.V. dba Interjet Deplaned               Mexico
                                                         Enplaned               Mexico
                Aer Lingus                               Deplaned               Europe
                                                         Enplaned               Europe
                Aeromexico                               Deplaned               Mexico
                                                         Enplaned               Mexico
                Air Canada                               Deplaned               Canada
                                                         Enplaned               Canada
                Air China                                Deplaned                 Asia
                                                         Enplaned                 Asia

                                                                            Price Category Code  \
Activity Period Operating Airline                        Activity Type Code
201803          ABC Aerolineas S.A. de C.V. dba Interjet Deplaned                         Other
                                                         Enplaned                         Other
                Aer Lingus                               Deplaned                         Other
                                                         Enplaned                         Other
                Aeromexico                               Deplaned                         Other
                                                         Enplaned                         Other
                Air Canada                               Deplaned                         Other
                                                         Enplaned                         Other
                Air China                                Deplaned                         Other
                                                         Enplaned                         Other

                                                                                  Terminal  \
Activity Period Operating Airline                        Activity Type Code
201803          ABC Aerolineas S.A. de C.V. dba Interjet Deplaned            International
                                                         Enplaned            International
                Aer Lingus                               Deplaned            International
                                                         Enplaned            International
                Aeromexico                               Deplaned            International
                                                         Enplaned            International
                Air Canada                               Deplaned            International
                                                         Enplaned            International
                Air China                                Deplaned            International
                                                         Enplaned            International

                                                                            Boarding Area  \
Activity Period Operating Airline                        Activity Type Code
201803          ABC Aerolineas S.A. de C.V. dba Interjet Deplaned                       A
                                                         Enplaned                       A
                Aer Lingus                               Deplaned                       G
                                                         Enplaned                       G
                Aeromexico                               Deplaned                       A
                                                         Enplaned                       A
                Air Canada                               Deplaned                       G
                                                         Enplaned                       G
                Air China                                Deplaned                       G
                                                         Enplaned                       G

                                                                             Passenger Count
Activity Period Operating Airline                        Activity Type Code
201803          ABC Aerolineas S.A. de C.V. dba Interjet Deplaned                       1090
                                                         Enplaned                       1212
                Aer Lingus                               Deplaned                       7165
                                                         Enplaned                       6992
                Aeromexico                               Deplaned                      12334
                                                         Enplaned                      12125
                Air Canada                               Deplaned                      36266
                                                         Enplaned                      38934
                Air China                                Deplaned                       9154
                                                         Enplaned                       9577